export const UI_COPY = {
  controls: {
    movementTitle: "Movement",
    riseLabel: "Rise",
    tiltLabel: "Tilt",
    swingLabel: "Swing",
    focusTitle: "Focus",
    focusDistanceLabel: "Focus distance",
    apertureTitle: "Aperture",
    resetTitle: "Reset",
    resetMovementsButton: "Reset movements",
    restartTaskButton: "Restart task",
    viewOptionsTitle: "View Options",
    geometryViewLabel: "Geometry view",
    geometryViewSide: "Side",
    geometryViewTop: "Top",
    geometryViewScheimpflug: "Scheimpflug Section",
    groundGlassAssistLabel: "Ground glass assist",
    focusAssistLabel: "Focus assist",
    gridLabel: "Grid",
    guidedControlLockedReason: "Disabled for this guided task",
    cameraMovementTitle: "Camera Movement",
    cameraMovementIntro: "Explore viewpoint and standard movements continuously.",
    viewpointTitle: "Viewpoint",
    viewpointCopy: "Move the whole camera lower or higher while keeping the standards neutral.",
    viewpointLower: "Lower",
    viewpointNeutral: "Neutral",
    viewpointHigher: "Higher",
    tiltTitle: "Tilt",
    tiltCopy: "Tilt the front or rear standard while the camera remains at the neutral viewpoint.",
    tiltFrontStandard: "Front standard",
    tiltRearStandard: "Rear standard",
    tiltNegative: "Negative",
    tiltZero: "Zero",
    tiltPositive: "Positive",
    verticalFramingTitle: "Vertical Framing",
    verticalFramingCopy: "Move the front or rear standard vertically to frame a lower or higher part of the subject.",
    verticalFramingGroupLabel: "Vertical framing standard",
    verticalFramingLower: "Lower",
    verticalFramingMiddle: "Middle",
    verticalFramingUpper: "Upper",
  },
  simulator: {
    freePracticeMode: "Free practice mode",
    scoreLabel: "Score",
    noEvaluationYet: "No evaluation yet.",
    criteriaLabel: "Criteria",
    primaryFeedbackLabel: "Primary feedback",
    secondaryFeedbackLabel: "Secondary feedback",
    geometryTitle: "2D Geometry",
    tiltLabel: "Tilt",
    swingLabel: "Swing",
    groundGlassTitle: "Ground Glass",
    groundGlassZoomIn: "Zoom in",
    groundGlassZoomOut: "Zoom out",
    groundGlassRenderPipeline: "Ground glass pipeline",
    groundGlassCurrentSettings: "Current settings",
    groundGlassFocusTargets: "Focus targets",
    sceneTitle: "3D Scene",
    sceneViewReset: "Reset 3D view",
    sceneViewFocusLabel: "View Focus",
    sceneViewFocusScene: "Scene",
    sceneViewFocusCamera: "Camera",
    focusPlaneOverlayLabel: "Show focus plane",
    dofOverlayLabel: "Show DOF region",
    renderQualityLabel: "Render quality",
    renderQualityHigh: "High",
    renderQualityStandard: "Standard",
    renderQualityLow: "Low",
    showOpticalGeometry: "Show optical geometry",
    hideOpticalGeometry: "Hide optical geometry",
    showScheimpflugConstruction: "Show Scheimpflug construction",
    hideScheimpflugConstruction: "Hide Scheimpflug construction",
    showLegends: "Show legends",
    hideLegends: "Hide legends",
    webglUnavailable: "WebGL is unavailable in this browser. Please use a WebGL-capable browser on desktop.",
    retryLoadScene: "Retry loading scene",
    sceneLoadFailed: "Scene load failed",
    unknownScenePrefix: "Unknown scene",
    opticsFallbackPrefix: "Optics fallback active",
    scenePickerLabel: "Scene",
    taskObjectiveLabel: "Objective",
    taskConstraintsLabel: "Constraints",
    taskAllowedControlsLabel: "Allowed controls",
    criterionCurrentLabel: "Current",
    criterionExpectedLabel: "Expected",
    taskCompletedTitle: "Task completed",
    taskCompletedSummaryLabel: "Final settings",
    freePracticeIntro: "Explore the scene without a scored task.",
    noScoredTask: "No scored task",
    notStarted: "Not started",
    inProgress: "In progress",
    completed: "Completed",
    desktopExperienceTitle: "Desktop browser recommended",
    desktopExperienceBody: "The simulator is designed for a desktop browser with WebGL and a wider screen. On a phone, tablet, or narrow browser window, the 3D Scene and Ground Glass may be unavailable or difficult to use.",
    desktopExperienceNarrowline: "For the best experience, use a desktop browser with a window at least 1024 px wide.",
    guidedTaskLabel: "Guided task",
    taskRequirementsLabel: "Task requirements",
    allowedControlsLabel: "Allowed controls",
    requirementsMetLabel: "Requirements met",
    nextAdjustmentLabel: "Next adjustment",
    viewRequirementsLabel: "View requirements",
    noAdjustmentNeeded: "No adjustment needed",
  },
  render: {
    groundGlassPreview: "Ground glass preview",
    focusAssistBadge: "Focus assist",
    focusStatusSharp: "Sharp",
    focusStatusAcceptable: "Near-sharp",
    focusStatusSoft: "Blurred",
    sceneAssetLoadFailedPrefix: "Failed to load scene assets for",
  },
} as const;
