export const UI_COPY = {
  controls: {
    movementTitle: "Movement",
    riseLabel: "Rise",
    tiltLabel: "Tilt",
    swingLabel: "Swing",
    focusTitle: "Focus",
    focusDistanceLabel: "Focus distance",
    apertureTitle: "Aperture",
    resetTitle: "Reset",
    resetMovementsButton: "Reset movements",
    restartTaskButton: "Restart task",
    viewOptionsTitle: "View Options",
    geometryViewLabel: "Geometry view",
    geometryViewSide: "Side",
    geometryViewTop: "Top",
    groundGlassAssistLabel: "Ground glass assist",
    focusAssistLabel: "Focus assist",
    gridLabel: "Grid",
    guidedControlLockedReason: "Disabled for this guided task",
    helpButton: "Help",
    helpTitle: "Movement help",
    helpRise: "Rise shifts framing upward without tilting the camera body.",
    helpTilt: "Tilt rotates the lens board on X axis to align focus along depth.",
    helpSwing: "Swing rotates the lens board on Y axis to align focus diagonally.",
    closeHelpButton: "Close help",
  },
  simulator: {
    taskTitle: "Task",
    freePracticeMode: "Free practice mode",
    feedbackTitle: "Feedback",
    scoreLabel: "Score",
    noEvaluationYet: "No evaluation yet.",
    criteriaLabel: "Criteria",
    primaryFeedbackLabel: "Primary feedback",
    secondaryFeedbackLabel: "Secondary feedback",
    geometryTitle: "2D Geometry",
    tiltLabel: "Tilt",
    swingLabel: "Swing",
    groundGlassTitle: "Ground Glass",
    groundGlassZoomIn: "Zoom in",
    groundGlassZoomOut: "Zoom out",
    groundGlassRenderPipeline: "Ground glass pipeline",
    groundGlassCurrentSettings: "Current settings",
    groundGlassFocusTargets: "Focus targets",
    sceneTitle: "3D Scene",
    sceneViewReset: "Reset 3D view",
    focusPlaneOverlayLabel: "Show focus plane",
    dofOverlayLabel: "Show DOF region",
    renderQualityLabel: "Render quality",
    renderQualityHigh: "High",
    renderQualityStandard: "Standard",
    renderQualityLow: "Low",
    showOpticalGeometry: "Show optical geometry",
    hideOpticalGeometry: "Hide optical geometry",
    showLegends: "Show legends",
    hideLegends: "Hide legends",
    webglUnavailable: "WebGL is unavailable in this browser. Please use a WebGL-capable browser on desktop.",
    retryLoadScene: "Retry loading scene",
    sceneLoadFailed: "Scene load failed",
    unknownScenePrefix: "Unknown scene",
    opticsFallbackPrefix: "Optics fallback active",
    scenePickerLabel: "Scene",
    taskObjectiveLabel: "Objective",
    taskConstraintsLabel: "Constraints",
    taskAllowedControlsLabel: "Allowed controls",
    criterionCurrentLabel: "Current",
    criterionExpectedLabel: "Expected",
    taskCompletedTitle: "Task completed",
    taskCompletedSummaryLabel: "Final settings",
    freePractice: "Free practice",
    freePracticeIntro: "Explore the scene without a scored task.",
    noScoredTask: "No scored task",
    notStarted: "Not started",
    inProgress: "In progress",
    completed: "Completed",
    liveObservation: "Live observation",
    changesReflected: "Changes are reflected immediately in the 3D Scene, Ground Glass, Current Settings, and Focus Targets.",
    guidedTaskLabel: "Guided task",
    taskRequirementsLabel: "Task requirements",
    allowedControlsLabel: "Allowed controls",
    requirementsMetLabel: "Requirements met",
    nextAdjustmentLabel: "Next adjustment",
    viewRequirementsLabel: "View requirements",
    noAdjustmentNeeded: "No adjustment needed",
  },
  render: {
    groundGlassPreview: "Ground glass preview",
    focusAssistBadge: "Focus assist",
    focusStatusSharp: "Sharp",
    focusStatusAcceptable: "Near-sharp",
    focusStatusSoft: "Blurred",
    sceneAssetLoadFailedPrefix: "Failed to load scene assets for",
  },
} as const;
