export const UI_COPY = {
  controls: {
    movementTitle: "Movement",
    riseLabel: "Rise",
    tiltLabel: "Tilt",
    swingLabel: "Swing",
    focusTitle: "Focus",
    focusDistanceLabel: "Focus distance",
    apertureTitle: "Aperture",
    resetTitle: "Reset",
    resetMovementsButton: "Reset movements",
    restartTaskButton: "Restart task",
    viewOptionsTitle: "View Options",
    geometryViewLabel: "Geometry view",
    geometryViewSide: "Side",
    geometryViewTop: "Top",
    groundGlassAssistLabel: "Ground glass assist",
    focusAssistLabel: "Focus assist",
    gridLabel: "Grid",
  },
  simulator: {
    taskTitle: "Task",
    freePracticeMode: "Free practice mode",
    feedbackTitle: "Feedback",
    scoreLabel: "Score",
    noEvaluationYet: "No evaluation yet.",
    criteriaLabel: "Criteria",
    primaryFeedbackLabel: "Primary feedback",
    secondaryFeedbackLabel: "Secondary feedback",
    geometryTitle: "2D Geometry",
    tiltLabel: "Tilt",
    swingLabel: "Swing",
    groundGlassTitle: "Ground Glass",
    groundGlassZoomIn: "Zoom in",
    groundGlassZoomOut: "Zoom out",
    groundGlassRenderPipeline: "Ground glass pipeline",
    groundGlassCurrentSettings: "Current settings",
    groundGlassFocusTargets: "Focus targets",
    sceneTitle: "3D Scene",
    sceneViewReset: "Reset 3D view",
    focusPlaneOverlayLabel: "Show focus plane",
    dofOverlayLabel: "Show DOF region",
    renderQualityLabel: "Render quality",
    renderQualityHigh: "High",
    renderQualityStandard: "Standard",
    renderQualityLow: "Low",
    webglUnavailable: "WebGL is unavailable in this browser. Please use a WebGL-capable browser on desktop.",
    retryLoadScene: "Retry loading scene",
    sceneLoadFailed: "Scene load failed",
    unknownScenePrefix: "Unknown scene",
    opticsFallbackPrefix: "Optics fallback active",
  },
  render: {
    groundGlassPreview: "Ground glass preview",
    focusAssistBadge: "Focus assist",
    focusStatusSharp: "Sharp",
    focusStatusAcceptable: "Near-sharp",
    focusStatusSoft: "Blurred",
    sceneAssetLoadFailedPrefix: "Failed to load scene assets for",
  },
} as const;
