import type { TaskDefinition } from "../../types/task";

const riseTask: TaskDefinition = {
  id: "rise-01",
  sceneId: "architecture-rise",
  title: "Lift composition with rise",
  mode: "guided",
  enabledControls: ["rise", "focusDistance", "aperture", "geometryView"],
  constraints: {
    movement: "rise-only",
    notes: ["Use rise without tilt or swing to frame the building top."],
  },
  criteria: [
    {
      id: "rise-building-top-visible",
      label: "Building top visibility is at least 95%",
      type: "composition-visible",
      targetId: "building-top",
      minimumCoverage: 0.95,
    },
    {
      id: "rise-building-main-visible",
      label: "Main building visibility is at least 70%",
      type: "composition-visible",
      targetId: "building-main-body",
      minimumCoverage: 0.7,
    },
    {
      id: "rise-movement-used",
      label: "Rise movement is used",
      type: "movement-used",
      movement: "rise",
      minimumAbs: 12,
    },
    {
      id: "rise-movement-range",
      label: "Rise remains within 12mm to 35mm",
      type: "movement-range",
      movement: "rise",
      min: 12,
      max: 35,
    },
  ],
  feedbackRules: {
    passPrimary: "You used rise to include the building top without tilting the camera body.",
    defaultFailPrimary: "Increase rise while keeping tilt and swing at 0°.",
    failPrimaryByCriterionId: {
      "rise-building-top-visible": "Building top is still clipped. Increase rise further.",
      "rise-building-main-visible": "Main building coverage is too low. Reduce excessive rise slightly.",
      "rise-movement-used": "Rise is too low for this composition task.",
      "rise-movement-range": "Keep rise between 12mm and 35mm for this exercise.",
    },
    failSecondaryByCriterionId: {
      "rise-building-top-visible": "Check the ground glass top edge and keep verticals stable.",
      "rise-building-main-visible": "Reframe so the body stays centered while retaining the top.",
      "rise-movement-used": "Start from about 15mm and fine-tune upward.",
      "rise-movement-range": "Avoid solving this by tilt; use rise-only framing.",
    },
  },
  initialCameraState: {
    frontRiseMm: 0,
    frontTiltDeg: 0,
    frontSwingDeg: 0,
    focusDistanceMm: 7200,
    aperture: 11,
    geometryView: "side",
    groundGlassAssistEnabled: false,
    focusAssistEnabled: false,
    gridEnabled: true,
  },
};

const tiltTask: TaskDefinition = {
  id: "tilt-01",
  sceneId: "table-tilt",
  title: "Align tabletop focus with tilt",
  mode: "guided",
  enabledControls: ["tilt", "focusDistance", "aperture", "geometryView"],
  constraints: {
    movement: "tilt-only",
    notes: ["Use front tilt to align the focus plane with the table surface."],
  },
  criteria: [
    {
      id: "tilt-allowed-aperture",
      label: "Aperture is one of f/5.6, f/11, f/22",
      type: "allowed-aperture",
      allowedApertures: [5.6, 11, 22],
    },
    {
      id: "tilt-near-sharp",
      label: "Near target is sharp",
      type: "focus-targets-sharp",
      targetIds: ["near-cup"],
      minimumSharpness: 0.8,
    },
    {
      id: "tilt-mid-sharp",
      label: "Middle target is sharp",
      type: "focus-targets-sharp",
      targetIds: ["mid-notebook"],
      minimumSharpness: 0.8,
    },
    {
      id: "tilt-far-sharp",
      label: "Far target is sharp",
      type: "focus-targets-sharp",
      targetIds: ["far-book"],
      minimumSharpness: 0.8,
    },
    {
      id: "tilt-movement-used",
      label: "Tilt is used",
      type: "movement-used",
      movement: "tilt",
      minimumAbs: 1.5,
    },
    {
      id: "tilt-movement-range",
      label: "Tilt remains within 1.5° to 8°",
      type: "movement-range",
      movement: "tilt",
      min: 1.5,
      max: 8,
    },
  ],
  feedbackRules: {
    passPrimary: "Great. You aligned focus across near, mid, and far targets with tilt.",
    defaultFailPrimary: "Adjust focus, then tilt to align the focus plane with the tabletop.",
    failPrimaryByCriterionId: {
      "tilt-allowed-aperture": "Do not use f/32. Solve this with tilt and focus.",
      "tilt-near-sharp": "Near target is soft. Reduce tilt or refine focus slightly closer.",
      "tilt-mid-sharp": "Middle target is soft. Re-balance focus and tilt angle.",
      "tilt-far-sharp": "Far target is soft. Increase tilt a little or refocus farther.",
      "tilt-movement-used": "Tilt is too small. Increase tilt to at least 1.5°.",
      "tilt-movement-range": "Tilt is outside the guided range (1.5° to 8°).",
    },
    failSecondaryByCriterionId: {
      "tilt-allowed-aperture": "Set aperture to f/22 or wider and use geometry to solve sharpness.",
      "tilt-near-sharp": "Check side-view diagram for focus-plane intersection with the tabletop.",
      "tilt-mid-sharp": "Aim for a balanced focus plane before fine focus tweaks.",
      "tilt-far-sharp": "Side view should show focus plane extending to the far book.",
      "tilt-movement-used": "Start around 2° and iterate.",
      "tilt-movement-range": "Large tilt often throws near or far objects out of focus.",
    },
  },
  initialCameraState: {
    frontRiseMm: 0,
    frontTiltDeg: 0,
    frontSwingDeg: 0,
    focusDistanceMm: 2400,
    aperture: 11,
    geometryView: "side",
    groundGlassAssistEnabled: false,
    focusAssistEnabled: false,
    gridEnabled: true,
  },
};

const swingTask: TaskDefinition = {
  id: "swing-01",
  sceneId: "shelf-swing",
  title: "Align diagonal focus with swing",
  mode: "guided",
  enabledControls: ["swing", "focusDistance", "aperture", "geometryView"],
  constraints: {
    movement: "swing-only",
    notes: ["Use front swing to align focus along the diagonal shelf."],
  },
  criteria: [
    {
      id: "swing-allowed-aperture",
      label: "Aperture is one of f/5.6, f/11, f/22",
      type: "allowed-aperture",
      allowedApertures: [5.6, 11, 22],
    },
    {
      id: "swing-front-sharp",
      label: "Front target is sharp",
      type: "focus-targets-sharp",
      targetIds: ["shelf-front"],
      minimumSharpness: 0.8,
    },
    {
      id: "swing-middle-sharp",
      label: "Middle target is sharp",
      type: "focus-targets-sharp",
      targetIds: ["shelf-middle"],
      minimumSharpness: 0.8,
    },
    {
      id: "swing-back-sharp",
      label: "Back target is sharp",
      type: "focus-targets-sharp",
      targetIds: ["shelf-back"],
      minimumSharpness: 0.8,
    },
    {
      id: "swing-movement-used",
      label: "Swing is used",
      type: "movement-used",
      movement: "swing",
      minimumAbs: 1.5,
    },
    {
      id: "swing-movement-range",
      label: "Swing remains within 1.5° to 8°",
      type: "movement-range",
      movement: "swing",
      min: 1.5,
      max: 8,
    },
  ],
  feedbackRules: {
    passPrimary: "Great. You used swing to align focus across the diagonal subject layout.",
    defaultFailPrimary: "Adjust swing direction and focus until all shelf targets are sharp.",
    failPrimaryByCriterionId: {
      "swing-allowed-aperture": "Do not use f/32. Solve this with swing and focus.",
      "swing-front-sharp": "Front shelf target is soft. Recheck swing direction and focus.",
      "swing-middle-sharp": "Middle shelf target is soft. Fine-tune swing and focus balance.",
      "swing-back-sharp": "Back shelf target is soft. Increase swing magnitude slightly.",
      "swing-movement-used": "Swing is too small. Increase swing to at least 1.5°.",
      "swing-movement-range": "Swing is outside the guided range (1.5° to 8°).",
    },
    failSecondaryByCriterionId: {
      "swing-allowed-aperture": "Use f/22 or wider and solve with geometry.",
      "swing-front-sharp": "Top-view diagram should show focus plane crossing front and mid targets.",
      "swing-middle-sharp": "Keep swing direction consistent with the shelf diagonal.",
      "swing-back-sharp": "Top-view focus plane should extend through the back shelf marker.",
      "swing-movement-used": "Start around 2° swing and tune focus distance.",
      "swing-movement-range": "Excess swing often softens one end of the diagonal.",
    },
  },
  initialCameraState: {
    frontRiseMm: 0,
    frontTiltDeg: 0,
    frontSwingDeg: 0,
    focusDistanceMm: 3200,
    aperture: 11,
    geometryView: "top",
    groundGlassAssistEnabled: false,
    focusAssistEnabled: false,
    gridEnabled: true,
  },
};

export const taskRegistry: Record<string, TaskDefinition> = {
  "rise-01": riseTask,
  "tilt-01": tiltTask,
  "swing-01": swingTask,
};

export const getTaskById = (taskId: string): TaskDefinition | undefined => taskRegistry[taskId];
